# logic.py

print("----------and(비트 연산자 &)---------")
print(True & True)
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print("----------or(비트 연산자 |)---------")
print(True | True)
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print("----------not---------")
print(not True)
print(not False)
print("----------비트연산자에서는 ~로 비트 반전---------")
print("음수 = 비트 반전 + 1 <=> 비트 반전 = 음수 - 1")
print("~True = ~1 = -1 -1")
print(~True)